/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.1, 0.56, -0.2]} rotation={[1.59, 0, -2.73]} scale={0.01}>
        <group position={[3.77, -3.31, -2.76]} rotation={[0.01, 0, 0]}>
          <mesh geometry={nodes.backlight.geometry} material={materials.rear_lights} position={[0, -123.02, -9.03]} />
          <mesh geometry={nodes.headlight.geometry} material={materials.headlight} position={[0, 98.02, -10.95]} />
        </group>
        <group position={[3.75, -15.01, -28.09]} rotation={[0.01, 0, 0]}>
          <mesh geometry={nodes.ID56.geometry} material={materials.glass} />
          <mesh geometry={nodes.ID56_1.geometry} material={materials.car_body_1} />
          <mesh geometry={nodes.ID56_2.geometry} material={materials.car_body} />
        </group>
        <mesh geometry={nodes.front_fender.geometry} material={materials.car_body} position={[3.77, 45.69, 9.86]} rotation={[0.01, 0, 0]} />
        <mesh geometry={nodes.lattice1.geometry} material={materials.engine_grille} position={[3.66, 96.27, -6.43]} rotation={[0.1, 0, 0]} />
        <mesh geometry={nodes.rear_fender.geometry} material={materials.car_body} position={[3.77, -81.02, 5.08]} rotation={[0.01, 0, 0]} />
        <group position={[3.77, -78.41, 18.14]} rotation={[0.01, 0, 0]}>
          <mesh geometry={nodes.ID84.geometry} material={materials.wheels} />
          <mesh geometry={nodes.ID84_1.geometry} material={materials.car_body_1} />
          <mesh geometry={nodes.ID84_2.geometry} material={materials.car_body} />
        </group>
        <group position={[3.77, -3.31, -2.76]} rotation={[0.01, 0, 0]}>
          <mesh geometry={nodes.ID93.geometry} material={materials.wheels} />
          <mesh geometry={nodes.ID93_1.geometry} material={materials.car_body_1} />
          <mesh geometry={nodes.ID93_2.geometry} material={materials.car_body} />
        </group>
      </group>
      <mesh geometry={nodes.platform.geometry} material={materials.Platform} position={[-0.04, 0.18, -0.05]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/car.gltf')
